[package]
name = "palettize"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Library for applying ordered Bayer dithering to images with custom color palettes"
license.workspace = true
repository.workspace = true
keywords = ["dithering", "image", "bayer", "palette"]
categories = ["multimedia::images"]
readme = "README.md"

[lints]
workspace = true

[dependencies]
image.workspace = true
